package com.mnu.capstoneapp;

import com.mnu.capstoneapp.Response.LoginResponse;

import java.util.Map;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.Headers;
import retrofit2.http.POST;

public interface APIservice {

    //로그인
    @POST("/login/")
    Call<LoginResponse> getLoginResponse(@Body Map request);


    //회원가입
    @POST("/signup/")
    Call<LoginResponse> getSignupResponse(@Body Map request);



    //이미지 데이터 전송
    /***
     *
     *
     // Generated by curl-to-java: https://fivesmallq.github.io/curl-to-java

     Request request = Request.Post("https://dapi.kakao.com/v2/vision/text/ocr");
     HttpResponse httpResponse = request.execute().returnResponse();
     System.out.println(httpResponse.getStatusLine());
     request.setHeader("Content-Type", "multipart/form-data");
     request.setHeader("Authorization", "KakaoAK ${REST_API_KEY}");
     HttpResponse httpResponse = request.execute().returnResponse();
     System.out.println(httpResponse.getStatusLine());
     if (httpResponse.getEntity() != null) {
     String html = EntityUtils.toString(httpResponse.getEntity());
     System.out.println(html);
     }
     *
     * ***/



    @Headers({
            "Content-Type: multipart/form-data",
            "Authorization", "KakaoAK ${9a1ca247a8a58968ceef53e69d4187ef}"
    })
    @POST("v2/vision/text/ocr")
    Call<LoginResponse> getImgResponse(@Body byte[] bytes);
}
